import React from "react";
import Head from "next/head";

import HomeHeader from "~/components/HomeHeader";
import MainLayout from "~/components/Layout";
import Post from "~/components/Post";
import Tweet from "~/components/Tweet";

export default function Home() {
  return (
    <>
      <Head>
        <title>Home / Twitter</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainLayout className="relative" sidebar>
        <div className="w-[600px]">
          <HomeHeader />
          <Tweet />
          <Post />
        </div>
      </MainLayout>
    </>
  );
}
